spring:
    #----------------------------------包含的profile-------------------------------------
    profiles:
        include: op
    #------------------------------------jpa-----------------------------------------
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialects: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #-----------------------------------datasource--------------------------------------
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 80
        # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 获取连接等待超时的时间
        maxWait: 60000
        # 一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000

        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

        validationQuery: SELECT 'x'
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true

        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall
    #---------------------------------json------------------------------------
    jackson:
        serialization:
            fail-on-empty-beans: false
        serialization-inclusion: non_null
    #----------------------------------编码相关-------------------------------------
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    messages:
        encoding: UTF-8

#----------------------------------sprint cloud-------------------------------------
hystrix:
    command:
        search:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000

#----------------------------------编码相关-------------------------------------
server:
    tomcat:
        basedir: ./
        uri-encoding: UTF-8
        accesslog:
            directory: ./logs
            enabled: true
            prefix: admin_access_log
    servlet:
        context-path: /admin